global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s
scrape_configs:
  - job_name: spring
    honor_timestamps: true
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - apiSpring:8080
#localhost:8080